### ISSUE TITLE
[FEAT] - Generic Payload Model

### ISSUE THREAD

**Issue by codeprefect** [IyiKuyoro/slack-block-msg-kit#32]
**Is your feature request related to a problem? Please describe.**
The slack interaction router provider `(payload, respond)` where the `payload` is untyped.

**Describe the solution you'd like**
Imagine a payload class like

```
class Payload {
  user: ISlackUser
  team: ISlackTeam
}

class SubmissionPayload<T> {
   // everything on payload
   submission: T
}
```

**Describe alternatives you've considered**

**Is this feature required by the Slack API?**
Share a link to a resource that can help us.

**Additional context**

**Comment by IyiKuyoro** [comment]
Very nice idea. I was going to get on that soon but a lack of motivation has been my issue.
I will work on it right away.

Thanks @barakimam.
